### ISSUE TITLE
Message Command Incorrect

### ISSUE THREAD

**Issue by daLoach20** [Dogeek/ChatAggregator#5]
In the irc.py module, when you're getting the data from the irc server, I believe that the text syntax is incorrect.

It is currently:
`if text.startswith('PRIVMSG'): `

However, the way that twitch formats these texts is like:
`<nick>!<nick>@<nick>.tmi.twitch.tv PRIVMSG <chan> :<message>`

So we need to safely split the data and get the 2nd index and check that.

**Comment by sbordeyne** [comment]
good point
I'll test a few things, probably will end up with a regex for it

**Comment by sbordeyne** [comment]
Addressed in commit 8f421647a038df2fd83221509af92cb84880b16f
